### ISSUE TITLE
ISO-27002

### ISSUE THREAD

**Issue by Hazaled** [dwyl/ISO-27001-2013-information-technology-security#25]
Hey, 

First off all, thanks for making this!

I still have one question, do you maby also have a pdf link to the ISO 27002?

Thanks in advance

**Comment by nelsonic** [comment]
Hi @Hazaled the _first_ result on Google for "ISO-27002 pdf" has the Full PDF:
https://www.google.com/search?q=ISO-27002+pdf

![image](https://user-images.githubusercontent.com/194400/53736453-b03cf900-3e81-11e9-89ce-0db7d900061e.png)

http://www.slinfo.una.ac.cr/documentos/EIF402/ISO27001.pdf
![image](https://user-images.githubusercontent.com/194400/53736481-c5198c80-3e81-11e9-94a1-3d4a2e446169.png)

The _reason_ I have not linked to it directly in this repository is because I don't want iso.org bothering us with a "take down notice" for "hosting" the PDF. But it's _widely_ available online. 

# "_seek, and ye shall find_"

**Comment by Hazaled** [comment]
Thanks for you comment.
I already found this one, if you look at page 4 you can see this is nog the ISO 27002 but the ISO17799

![image](https://user-images.githubusercontent.com/48211504/53736804-17ab7680-3e8b-11e9-9f14-73e442f19b47.png)

**Comment by Hazaled** [comment]
Damn I see it now, sorry my bad thanks for your help!
